In [17]:
# # Day 4 – Data Science Fundamentals

# Topics:
# - What is Data Science?
# - Data Science workflow
# - Types of data
# - Real-world applications
# - Basic data analysis using Python

In [18]:
# ## What is Data Science?

# Data Science is the field of extracting useful insights and knowledge
# from data using programming, statistics, mathematics, and machine learning.

# A typical Data Science workflow includes:

# 1. Problem Definition
# 2. Data Collection
# 3. Data Cleaning
# 4. Exploratory Data Analysis
# 5. Feature Engineering
# 6. Model Building
# 7. Model Evaluation
# 8. Deployment
# 9. Monitoring

In [19]:
# ## Types of Data

# ### Structured Data
# Data organized in rows and columns, such as databases and spreadsheets.

# ### Unstructured Data
# Data such as images, videos, audio, and text.

# ### Semi-structured Data
# Data that contains some organizational structure, such as JSON and XML.

In [20]:
# ## Real-World Applications of Data Science

# - Healthcare – disease prediction and patient analysis
# - Finance – fraud detection and risk analysis
# - E-commerce – recommendation systems
# - Marketing – customer segmentation
# - Transportation – route optimization
# - Social Media – content recommendation
# - Education – student performance analysis

In [21]:
import pandas as pd

In [22]:
data ={
    "Name": ["Alice", "Bobby", "tom", "jeeyan", "Doraemon"],
    "Age": [24, 20, 19, 23, 20],
    "Marks": [90, 89, 99, 97, 91]

}
df = pd.DataFrame(data)
df

       Name  Age  Marks
0     Alice   24     90
1     Bobby   20     89
2       tom   19     99
3    jeeyan   23     97
4  Doraemon   20     91

In [23]:
print("First 5 names: ")
df.head()

First 5 names:

       Name  Age  Marks
0     Alice   24     90
1     Bobby   20     89
2       tom   19     99
3    jeeyan   23     97
4  Doraemon   20     91

In [24]:
print("Data information: ")
df.info()

Data information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   Marks   5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [25]:
print("Statistics:")
df.describe()

Statistics:

             Age      Marks
count   5.000000   5.000000
mean   21.200000  93.200000
std     2.167948   4.494441
min    19.000000  89.000000
25%    20.000000  90.000000
50%    20.000000  91.000000
75%    23.000000  97.000000
max    24.000000  99.000000

In [26]:
average_marks = df["Marks"].mean()

print("Average Marks:", average_marks)

Average Marks: 93.2

In [27]:
#calculate the highest marks
highest_marks = df["Marks"].max()

print("Highest Marks: ", highest_marks)

Highest Marks:  99

In [28]:
#Student with the highest marks

top_student = df.loc[df["Marks"].idxmax()]

print(top_student)

Name     tom
Age       19
Marks     99
Name: 2, dtype: object

In [29]:
#Simple Data Analysis
print("Average marks: ", df["Marks"].mean())
print("Average Age: ", df["Age"].mean())
print("Highest Marks: ", df["Marks"].max())
print("Lowest Marks: ", df["Marks"].min())
print("Number of students: ", len(df))

Average marks:  93.2
Average Age:  21.2
Highest Marks:  99
Lowest Marks:  89
Number of students:  5

In [30]:
# ## Conclusion

# In this module, I learned the fundamentals of Python and Data Science.
# I practiced Python programming, data structures, loops, functions,
# file handling, and basic data analysis using Pandas.

# I also explored the Data Science workflow and real-world applications.