In [2]:
import numpy as np
import pandas as pd

In [3]:
data = {
    "Name": [
        "Aarav", "Priya", "Rahul", "Sneha", "Aditya",
        "Ananya", "Rohan", "Neha", "Vikram", "Isha"
    ],
    "Age": [20, 21, 19, 20, 22, 21, 20, 19, 22, 21],
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],
    "Study_Hours": [3, 5, 2, 6, 4, 7, 3, 5, 2, 6],
    "Attendance": [85, 92, 78, 95, 88, 96, 82, 90, 75, 93],
    "Marks": [72, 88, 65, 91, 79, 95, 70, 86, 62, 90]
}

df = pd.DataFrame(data)

df

     Name  Age  Gender  Study_Hours  Attendance  Marks
0   Aarav   20    Male            3          85     72
1   Priya   21  Female            5          92     88
2   Rahul   19    Male            2          78     65
3   Sneha   20  Female            6          95     91
4  Aditya   22    Male            4          88     79
5  Ananya   21  Female            7          96     95
6   Rohan   20    Male            3          82     70
7    Neha   19  Female            5          90     86
8  Vikram   22    Male            2          75     62
9    Isha   21  Female            6          93     90

In [4]:
average_marks = df["Marks"].mean()

print("Average Marks:", average_marks)

Average Marks: 79.8

In [5]:
highest_marks = df["Marks"].max()

print("Highest Marks:", highest_marks)

Highest Marks: 95

In [6]:
lowest_marks = df["Marks"].min()

print("Lowest Marks:", lowest_marks)

Lowest Marks: 62

In [7]:
average_study_hours = df["Study_Hours"].mean()

print("Average Study Hours:", average_study_hours)

Average Study Hours: 4.3

In [8]:
average_attendance = df["Attendance"].mean()

print("Average Attendance:", average_attendance)

Average Attendance: 87.4

In [9]:
top_students = df.sort_values(
    by="Marks",
    ascending=False
)

top_students[["Name", "Marks"]].head()

     Name  Marks
5  Ananya     95
3   Sneha     91
9    Isha     90
1   Priya     88
7    Neha     86

In [10]:
high_performers = df[df["Marks"] > 80]

high_performers[["Name", "Marks"]]

     Name  Marks
1   Priya     88
3   Sneha     91
5  Ananya     95
7    Neha     86
9    Isha     90

In [11]:
gender_performance = df.groupby("Gender")["Marks"].mean()

print(gender_performance)

Gender
Female    90.0
Male      69.6
Name: Marks, dtype: float64

In [13]:
study_analysis = df[["Study_Hours", "Marks"]]

study_analysis

   Study_Hours  Marks
0            3     72
1            5     88
2            2     65
3            6     91
4            4     79
5            7     95
6            3     70
7            5     86
8            2     62
9            6     90

In [14]:
correlation = df[["Study_Hours", "Attendance", "Marks"]].corr()

correlation

             Study_Hours  Attendance     Marks
Study_Hours     1.000000    0.965780  0.986526
Attendance      0.965780    1.000000  0.986574
Marks           0.986526    0.986574  1.000000

In [ ]:
# # Key Insights

# Based on the analysis:

# 1. The average marks provide an overall measure of student performance.

# 2. Students with higher study hours generally show better academic
#    performance in this sample.

# 3. Attendance can be compared with marks to understand whether attendance
#    is associated with academic performance.

# 4. The highest and lowest performing students can be identified using
#    sorting and filtering.

# 5. Grouping the data by gender allows comparison of average performance
#    between groups.

# 6. Correlation analysis helps identify relationships between study hours,
#    attendance, and marks.

In [ ]:
# # Key Insights

# Based on the analysis:

# 1. The average marks provide an overall measure of student performance.

# 2. Students with higher study hours generally show better academic
#    performance in this sample.

# 3. Attendance can be compared with marks to understand whether attendance
#    is associated with academic performance.

# 4. The highest and lowest performing students can be identified using
#    sorting and filtering.

# 5. Grouping the data by gender allows comparison of average performance
#    between groups.

# 6. Correlation analysis helps identify relationships between study hours,
#   #  attendance, and marks.