In [2]:
import pandas as pd
import numpy as np

In [3]:
#importing dataset into the google colab

data = {
    "Name": [
        "Aarav", "Priya", "Rahul", "Sneha", "Aditya",
        "Ananya", "Rohan", "Neha", "Vikram", "Riya"
    ],
    "Age": [20, 21, 19, 20, 22, 21, 20, 19, 22, 21],
    "Gender": [
        "Male", "Female", "Male", "Female", "Male",
        "Female", "Male", "Female", "Male", "Female"
    ],
    "Study_Hours": [3, 5, 2, 6, 4, 7, 3, 5, 2, 6],
    "Attendance": [85, 92, 78, 95, 88, 96, 82, 90, 75, 93],
    "Marks": [72, 88, 65, 91, 79, 95, 70, 86, 62, 90]
}

student_df = pd.DataFrame(data)

student_df

     Name  Age  Gender  Study_Hours  Attendance  Marks
0   Aarav   20    Male            3          85     72
1   Priya   21  Female            5          92     88
2   Rahul   19    Male            2          78     65
3   Sneha   20  Female            6          95     91
4  Aditya   22    Male            4          88     79
5  Ananya   21  Female            7          96     95
6   Rohan   20    Male            3          82     70
7    Neha   19  Female            5          90     86
8  Vikram   22    Male            2          75     62
9    Riya   21  Female            6          93     90

In [4]:
student_df.to_csv("student_performance.csv", index=False)

print("CSV file created successfully!")

CSV file created successfully!

In [5]:
df = pd.read_csv("student_performance.csv")

df.head()

     Name  Age  Gender  Study_Hours  Attendance  Marks
0   Aarav   20    Male            3          85     72
1   Priya   21  Female            5          92     88
2   Rahul   19    Male            2          78     65
3   Sneha   20  Female            6          95     91
4  Aditya   22    Male            4          88     79

In [6]:
print("Number of rows and columns:", df.shape)

Number of rows and columns: (10, 6)

In [7]:
print("Column names:")
print(df.columns.tolist())

Column names:
['Name', 'Age', 'Gender', 'Study_Hours', 'Attendance', 'Marks']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         10 non-null     object
 1   Age          10 non-null     int64
 2   Gender       10 non-null     object
 3   Study_Hours  10 non-null     int64
 4   Attendance   10 non-null     int64
 5   Marks        10 non-null     int64
dtypes: int64(4), object(2)
memory usage: 612.0+ bytes

In [9]:
print("First 5 records:")
display(df.head())

First 5 records:

     Name  Age  Gender  Study_Hours  Attendance  Marks
0   Aarav   20    Male            3          85     72
1   Priya   21  Female            5          92     88
2   Rahul   19    Male            2          78     65
3   Sneha   20  Female            6          95     91
4  Aditya   22    Male            4          88     79

In [10]:
print("Last 5 records:")
display(df.tail())

Last 5 records:

     Name  Age  Gender  Study_Hours  Attendance  Marks
5  Ananya   21  Female            7          96     95
6   Rohan   20    Male            3          82     70
7    Neha   19  Female            5          90     86
8  Vikram   22    Male            2          75     62
9    Riya   21  Female            6          93     90

In [11]:
df.describe()

             Age  Study_Hours  Attendance      Marks
count  10.000000    10.000000   10.000000  10.000000
mean   20.500000     4.300000   87.400000  79.800000
std     1.080123     1.766981    7.214184  11.830281
min    19.000000     2.000000   75.000000  62.000000
25%    20.000000     3.000000   82.750000  70.500000
50%    20.500000     4.500000   89.000000  82.500000
75%    21.000000     5.750000   92.750000  89.500000
max    22.000000     7.000000   96.000000  95.000000